### ISSUE TITLE
What is the required libraries for java-rdfa to compile?

### ISSUE THREAD

**Issue by boanuge** [shellac/java-rdfa#38]
Hi shellac,
I tried to compile the project with JENA library path.
And I got following error.
nu.validator.htmlparser.sax.HtmlParser
It seems the project requires more than JENA library.
I would appreciate if you can list required libraries.
Kind regards,
boanuge

**Comment by shellac** [comment]
On 02/06/15 08:29, The Bible-smith wrote:
> Hi shellac,
> I tried to compile the project with JENA library path.
> And I got following error.
> nu.validator.htmlparser.sax.HtmlParser
> It seems the project requires more than JENA library.
> I would appreciate if you can list required libraries.
> Kind regards,
> boanuge

Using maven is by far the easiest way to build it, since that downloads 
all the dependencies.

What you're missing is the validator.nu html parser. See [1] for a 
download location.

Damian

[1] 
<http://search.maven.org/#artifactdetails|nu.validator|htmlparser|1.4.1|jar>

**Comment by boanuge** [comment]
Thank you very much for the nice tool. :)

**Comment by sschuberth** [comment]
@boanuge @shellac I guess this issue can be closed then?
